### ISSUE TITLE
Misspelling in cheatsheet title

### ISSUE THREAD

**Issue by puntofisso** [ch-bu/ggplot2-fundamentals#1]
Hi there, in [this cheatsheet](https://github.com/ch-bu/ggplot2-fundamentals/blob/main/cheatsheets/08_ggplot2_fundamentals_cheatsheet_expansion_continuous.pdf) the word "continuous" seems misspelled, according to both UK and US English dictionaries.

**Comment by ch-bu** [comment]
Hi. I don't see how it's misspelled. The Webster dictionary spells it the same way: https://www.merriam-webster.com/dictionary/continuous.

**Comment by puntofisso** [comment]
Indeed (unless I'm seeing a cached version?), there is a missing "u" before the "o" on the cheatsheet, 9 characters against the 10 of the Merriam-Webster version.

<img width="327" alt="Screenshot 2022-02-12 at 08 44 51" src="https://user-images.githubusercontent.com/612999/153704333-f553e084-3649-40f2-8f44-ff772b404180.png">

**Comment by ch-bu** [comment]
Thanks a ton! I have corrected the typos in the document.
